const $=(s)=>document.querySelector(s); let conversationId=null, activeProjectId=null, activeProject=null, busy=false;
async function api(url,options){const response=await fetch(url,options);const body=await response.json();if(!response.ok)throw Error(body.error||'请求没有完成。');return body;}
function escapeText(value){return String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
function today(){return new Date().toLocaleDateString('en-CA');}
function resetThread(){conversationId=null;$('#conversation-title').textContent='和 Heka 对话';$('#chat-thread').innerHTML='<article class="chat-message assistant"><span>HEKA / CLOUD</span><p>你想从哪件真实发生的事开始？我会把事实、推测和待验证的部分分开。</p></article>';$('#make-trace').disabled=true;$('#tool-context').hidden=true;$('#chat-feedback').textContent='这一段对话只在你发送时才会交给云端推理。形成 Trace 后，仍要由你审阅确认。';}
function add(role,text){const article=document.createElement('article');article.className=`chat-message ${role}`;article.innerHTML=`<span>${role==='user'?'你':'HEKA / CLOUD'}</span><p></p>`;article.querySelector('p').textContent=text;$('#chat-thread').append(article);article.scrollIntoView({behavior:'smooth',block:'end'});}
function renderMessages(messages){$('#chat-thread').innerHTML='';messages.forEach(message=>add(message.role,message.content));if(!messages.length)resetThread();}
function activeContext(){const label=activeProject?activeProject.title:'收集箱';$('#active-context').textContent=`${activeProject?'PROJECT':'INBOX'} / ${label}`;}
async function loadProjects(){const projects=await api('/api/v1/projects');const list=$('#project-list');list.innerHTML=projects.map(project=>`<button class="project-item ${activeProjectId===project.id?'active':''}" data-project="${project.id}"><span class="project-mark">◇</span><span><b>${escapeText(project.title)}</b><small>${project.trace_count} 条 Trace · ${project.conversation_count} 段对话</small></span></button>`).join('')||'<p class="empty-list">还没有长期项目。</p>';list.querySelectorAll('[data-project]').forEach(button=>button.onclick=()=>selectProject(projects.find(item=>item.id===Number(button.dataset.project))));}
async function loadConversations(){const suffix=activeProjectId?`?project_id=${activeProjectId}`:'';const conversations=await api(`/api/v1/conversations${suffix}`);const list=$('#conversation-list');list.innerHTML=conversations.map(item=>`<button class="conversation-item ${conversationId===item.id?'active':''}" data-conversation="${item.id}"><b>${escapeText(item.title)}</b><small>${new Date(item.updated_at).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'})}</small></button>`).join('')||'<p class="empty-list">这里还没有对话。<br/>开始一段新的记录吧。</p>';list.querySelectorAll('[data-conversation]').forEach(button=>button.onclick=()=>openConversation(Number(button.dataset.conversation),conversations));}
async function loadToday(){const traces=await api(`/api/v1/traces/day/${today()}`);$('#today-count').textContent=traces.length;const list=$('#today-trace-list');list.innerHTML=traces.length?traces.map(trace=>{const summary=trace.trace?.observable_facts?.[0]?.statement||trace.raw_text;return `<article class="today-trace-card"><span>${trace.proposal_status==='accepted'?'已确认':'待审阅'}</span><p>${escapeText(summary)}</p><small>${new Date(trace.created_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</small></article>`;}).join(''):'<article class="today-empty"><b>今天还没有 Trace</b><p>先从一段对话开始。信息足够时，Heka 才会邀请你形成候选。</p></article>';}
async function selectProject(project){activeProjectId=project?.id||null;activeProject=project||null;document.querySelectorAll('.project-item').forEach(node=>node.classList.remove('active'));$('#inbox-project').classList.toggle('active',!activeProjectId);activeContext();resetThread();await Promise.all([loadProjects(),loadConversations()]);}
async function openConversation(id,conversations){conversationId=id;const item=conversations?.find(row=>row.id===id);if(item)$('#conversation-title').textContent=item.title;const result=await api(`/api/v1/conversations/${id}`);renderMessages(result.messages);await loadConversations();}
async function send(){if(busy)return;const input=$('#chat-input'),text=input.value.trim(),feedback=$('#chat-feedback');if(!text)return;busy=true;input.value='';add('user',text);feedback.textContent='DeepSeek 正在理解，并按需读取相关资料…';try{const result=await api('/api/v1/conversations/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({conversation_id:conversationId,project_id:activeProjectId,text})});conversationId=result.conversation_id;$('#conversation-title').textContent=text.slice(0,30)+(text.length>30?'…':'');add('assistant',result.content);const context=$('#tool-context');context.hidden=!result.used_tools.length;context.textContent=result.used_tools.length?`本轮读取：${result.used_tools.join('、')}。这些工具不能写入模型。`:'';const ready=result.trace_readiness||{};$('#make-trace').disabled=!ready.ready;feedback.textContent=ready.ready?`这段对话已足够形成候选 Trace：${ready.reason}`:`暂不形成 Trace：${ready.reason}${ready.next_question?` 建议补充：${ready.next_question}`:''}`;await loadConversations();}catch(error){feedback.textContent=error.message;}finally{busy=false;}}
async function createProject(event){event.preventDefault();const title=$('#project-title-input').value.trim(),purpose=$('#project-purpose-input').value.trim();if(!title)return;try{const project=await api('/api/v1/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,purpose})});$('#project-dialog').close();$('#project-title-input').value='';$('#project-purpose-input').value='';await selectProject(project);}catch(error){$('#project-purpose-input').setCustomValidity(error.message);$('#project-purpose-input').reportValidity();}}
$('#send-chat').onclick=send;$('#chat-input').addEventListener('keydown',(event)=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)){event.preventDefault();send();}});$('#inbox-project').onclick=()=>selectProject(null);$('#new-conversation').onclick=resetThread;$('#new-conversation-top').onclick=resetThread;$('#new-project').onclick=()=>$('#project-dialog').showModal();$('#create-project').onclick=createProject;
$('#make-trace').onclick=async()=>{const feedback=$('#chat-feedback');if(!conversationId)return;try{feedback.textContent='云端正在把这段对话整理为待审阅的 Trace…';const result=await api(`/api/v1/conversations/${conversationId}/trace-candidate`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});feedback.textContent=`${result.message} 提案 #${result.proposal_id}`;$('#make-trace').disabled=true;await Promise.all([loadToday(),loadProjects()]);}catch(error){feedback.textContent=error.message;}};
(async()=>{activeContext();try{await Promise.all([loadProjects(),loadConversations(),loadToday()]);}catch(error){$('#chat-feedback').textContent=`无法读取本地资料：${error.message}`;}})();
