const q = (selector) => document.querySelector(selector);
async function request(url, options) { const response = await fetch(url, options); const body = await response.json(); if (!response.ok) throw Error(body.error || "请求失败。"); return body; }
function renderModel(model) { const area=q('#model-content'); const dimensions=Object.entries(model.confirmed_dimensions||{}); area.innerHTML=dimensions.length ? dimensions.map(([name,item])=>`<article class="dimension"><h3>${name}</h3><p>${Math.round(item.value*100)}% · 置信度 ${Math.round(item.confidence*100)}%</p><p>${item.scope}</p></article>`).join('') : '<p class="empty">模型仍是空白的。先完成初始自述，再建立一个由你确认的起点。</p>'; }
function renderEvolution(events) { q('#evolution-list').innerHTML=events.length ? events.map((item)=>`<article class="evolution-event"><p>${item.dimension}：${Math.round(item.delta*100)}%</p><p class="evolution-detail">依据 ${item.evidence.length} 条已确认案例</p></article>`).join('') : '<p class="empty">还没有足够的跨时间证据。</p>'; }
async function refresh() { const [model, events, report]=await Promise.all([request('/api/v1/model'),request('/api/v1/evolution'),request('/api/v1/onboarding')]); renderModel(model); q('#onboarding-panel').hidden=Boolean(report); q('#migration-panel').hidden=!report; renderEvolution(events); }
q('#onboarding-form').onsubmit=async(event)=>{ event.preventDefault(); const form=new FormData(event.currentTarget); const answers={opportunity:form.get('opportunity'),ambiguity:form.get('ambiguity'),tradeoff:form.get('tradeoff'),pressure:form.get('pressure'),support:form.get('support'),mbti:form.get('mbti')||'',current_focus:form.get('current_focus')||''}; const feedback=q('#onboarding-feedback'); try { await request('/api/v1/onboarding',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answers})}); feedback.textContent='已保存。现在可以用本周 Trace 建立初始模型。'; refresh(); } catch(error) { feedback.textContent=error.message; } };
q('#evolution-check').onclick=async()=>{ renderEvolution((await request('/api/v1/evolution/review',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"days":90}'})).events); };
q('#build-seed').onclick=async()=>{ const feedback=q('#seed-feedback'); const preview=q('#seed-preview'); try { feedback.textContent='本地模型正在整理初始自述与本周 Trace…'; const result=await request('/api/v1/model/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}); const seed=result.seed; preview.innerHTML=`<div class="seed-preview"><p class="eyebrow">初始自述 + ${result.source_count} 条本地 Trace</p><p>${seed.boundary}</p>${seed.dimensions.map((item)=>`<article><b>${item.name} · ${Math.round(item.value*100)}%</b><span>${item.scope}</span><small>${item.evidence.join('；')}</small></article>`).join('')}<button id="confirm-seed" class="primary">确认写入我的当前模型 <b>→</b></button></div>`; q('#confirm-seed').onclick=async()=>{ const confirmed=await request('/api/v1/model/bootstrap/confirm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seed})}); feedback.textContent=confirmed.message; preview.innerHTML=''; refresh(); }; feedback.textContent='这是候选初始模型；确认后才进入版本历史。'; } catch(error) { feedback.textContent=error.message; } };
refresh();
